/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package seila;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class seilaTela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(seilaTela.class.getName());
    
    DefaultTableModel model;
    
    private static final String CONCLUIDA = "Concluída!";
    private static final String NAO_CONCLUIDA = "Não concluída!";
    
    private final ArrayList<String> tarefas = new ArrayList<>();
    private final ArrayList<String> tarefasFiltradas = new ArrayList<>();
    /**
     * Creates new form seilaTela
     */
    public seilaTela() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        
        model = (DefaultTableModel) jTableTarefa.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDescTarefa = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jComboBoxFiltro = new javax.swing.JComboBox<>();
        jScrollPaneTarefas = new javax.swing.JScrollPane();
        jTableTarefa = new javax.swing.JTable();
        jButtonConcTarefa = new javax.swing.JButton();
        jButtonRemoveTarefa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAdd.setText("Adicionar");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Concluído", "Não Concluído" }));
        jComboBoxFiltro.addItemListener(this::jComboBoxFiltroItemStateChanged);

        jTableTarefa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tarefas", "Status"
            }
        ));
        jScrollPaneTarefas.setViewportView(jTableTarefa);

        jButtonConcTarefa.setText("Concluir");
        jButtonConcTarefa.addActionListener(this::jButtonConcTarefaActionPerformed);

        jButtonRemoveTarefa.setText("Remover");
        jButtonRemoveTarefa.addActionListener(this::jButtonRemoveTarefaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDescTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdd))
                    .addComponent(jScrollPaneTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonConcTarefa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonRemoveTarefa)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConcTarefa)
                    .addComponent(jButtonRemoveTarefa))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        if (jTextFieldDescTarefa.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "A descrição não pode ser vazia :C");
            return;
        }
        
        if (hasTarefaRepetida(jTextFieldDescTarefa.getText())){
            JOptionPane.showMessageDialog(null, "A tarefa " + jTextFieldDescTarefa.getText() + " já existe.");
        }
        
        tarefas.add(jTextFieldDescTarefa.getText() + ";" + NAO_CONCLUIDA);
        
        preencherTabela();
        
        jTextFieldDescTarefa.setText("");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRemoveTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveTarefaActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = jTableTarefa.getSelectedRow();
        
        if (linhaSelecionada < 0){
            JOptionPane.showMessageDialog(null, "Nenhuma tarefa foi selecionada.");
            return;
        }
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a tarefa?");
        
        String tarefaSelecionada = recuperarTarefa(linhaSelecionada);
        
        int indiceTarefaSelecionada = tarefas.indexOf(tarefaSelecionada);
        if (opcao == JOptionPane.YES_OPTION){
            tarefas.remove(indiceTarefaSelecionada);
            preencherTabela();
        }
        
        filtrarTabela();
        
        preencherTabela();
    }//GEN-LAST:event_jButtonRemoveTarefaActionPerformed

    private void jButtonConcTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcTarefaActionPerformed
        // TODO add your handling code here:
        
        int linhaSelecionada = jTableTarefa.getSelectedRow();
        
        if (linhaSelecionada < 0){
            JOptionPane.showMessageDialog(null, "Nenhuma tarefa foi selecionada.");
            return;
        }
        
        String tarefaSelecionada = recuperarTarefa(linhaSelecionada);
        
        int indiceTarefaSelecionada = tarefas.indexOf(tarefaSelecionada);
        
        String[] dados = tarefas.get(indiceTarefaSelecionada).split(";");
        tarefas.set(indiceTarefaSelecionada, dados[0] + ";" + CONCLUIDA);
        
        filtrarTabela();
        
        preencherTabela();
    }//GEN-LAST:event_jButtonConcTarefaActionPerformed

    private void jComboBoxFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFiltroItemStateChanged
        // TODO add your handling code here:
        filtrarTabela();
        
        preencherTabela();
    }//GEN-LAST:event_jComboBoxFiltroItemStateChanged
    
    private void filtrarTabela(){
        int opcao = jComboBoxFiltro.getSelectedIndex();
        tarefasFiltradas.clear();
        
        String[] dados;
        for(String tarefa : tarefas){
            dados = tarefa.split(";");
            
            switch (opcao) {
                case 0:
                    tarefasFiltradas.add(tarefa);
                    break;
                case 1:
                    if (dados[1].equals(CONCLUIDA)){
                        tarefasFiltradas.add(tarefa);
                    }
                    break;
                case 2:
                    if (dados[1].equals(NAO_CONCLUIDA)){
                        tarefasFiltradas.add(tarefa);
                    }
                    break;    
                default:
                    throw new AssertionError();
            }
        }
    }
    
    private String recuperarTarefa(int indiceTarefa){
        if (jComboBoxFiltro.getSelectedIndex() > 0){
            return tarefasFiltradas.get(indiceTarefa);
        }else{
            return tarefas.get(indiceTarefa);
        }
    }
    
    public boolean hasTarefaRepetida(String novaTarefa){
        for (String tarefa : tarefas){
            String dados[] = tarefa.split(";");
            if (novaTarefa.toLowerCase().equals(dados[0].toLowerCase())){
                return true;
            }
        }
        
        return false;
    }
    
    private void preencherTabela(){
        ArrayList<String> listaTarefas;
        
        if (jComboBoxFiltro.getSelectedIndex() > 0){
            listaTarefas = tarefasFiltradas;    
        }else{
            listaTarefas = tarefas;
        }
        
        model.setRowCount(0);
        
        for (String tarefa : listaTarefas){
            String[] dados = tarefa.split(";");
            
            model.addRow(new Object[]{
                dados[0],
                dados[1]
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new seilaTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonConcTarefa;
    private javax.swing.JButton jButtonRemoveTarefa;
    private javax.swing.JComboBox<String> jComboBoxFiltro;
    private javax.swing.JScrollPane jScrollPaneTarefas;
    private javax.swing.JTable jTableTarefa;
    private javax.swing.JTextField jTextFieldDescTarefa;
    // End of variables declaration//GEN-END:variables
}
